Milestone: Popup menu
Gmanlove/My-Portfolio pull request #10
Opened 2023-02-01 10:56 UTC by Gmanlove

### **In this milestone, we implemented the following requirements:**
 - [ ] Installed linters configurations and made sure there are no linter error
- [ ] Used HTML, CSS and Javascript to build the popup of the portfolio website
- [ ] Make the project button popup with the details about the project.
- [ ] When clicked, the close (X) button, makes the popup disappears.
- [ ] We use a JavaScript array to store all of the information for all projects.
- [ ] We implemented mobile and desktop screen sizes popups to match figma design.

2023-02-01 11:33 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Gmanlove, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub workflow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 11:33 UTC, leonardodiasb commented on script.js
> +  </div>
- [ ] You did a great job by creating the projects section dynamically with JS, but the cards do not have a separation and they look like they are 'glued' together. Kindly divide each card so they can have a gap between them and look more like the Figma template. (look that in the HTML code, you created each card is not a separate `div`)
 - [ ] Also the titles of each card are missing. Please implement them to make them look more professional.
 - Your design:
 - 
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/61919617/216030199-fc52b827-f2bc-4060-953c-51dec8cbd5b3.png">

 - Figma template:
 - 
<img width="719" alt="image" src="https://user-images.githubusercontent.com/61919617/216030395-7f07fa19-ce3b-4f99-b2e3-9a80a7cfb4a5.png">

2023-02-01 11:33 UTC, leonardodiasb commented on script.js
> +    </div>
- [ ] The modal is very similar to the Figma design, but it's currently too big not fitting on any screen on the desktop and mobile view. Kindly make them responsive so they can fit on every screen and the user is able to see all the content of the modal without the need of scrolling up and down for a better user experience. (You could reduce the description, the image size, etc.)
 - Your design:
 - 

<img width="1150" alt="image" src="https://user-images.githubusercontent.com/61919617/216031176-b73b671b-4006-44a2-8cbf-b16ad25ec880.png">
<img width="473" alt="image" src="https://user-images.githubusercontent.com/61919617/216031241-899ad224-e3c2-4aeb-859e-bbf0dbaef5fe.png">

2023-02-02 07:00 UTC, TuyishimireEric requested changes
# Status: REQUIRED CHANGES :recycle: 
### Hi  @Gmanlove   👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

## Highlights 
✔️ Professional PR. 👍
✔️ Professional Readme. 👍

## Required Changes ♻️

- [ ] **Check the comments below 👇**

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 07:00 UTC, TuyishimireEric commented on script.js
> +  </div>
- [ ] **Good job on adding the title on your cards 👍** however, as suggested by the previous reviewer, it would be better to separate the cards to replicate the Figma design 😎😎😎😎. 

   - You styled this section in CSS with ```grid-template-columns: repeat(2, 1fr);``` and this CSS property sets the number of columns in a grid container and the size of each column. The value "repeat(2, 1fr)" means that the grid container has 2 columns, each with a fractional unit of 1, so they each take up equal parts of the available space. I think this is the cause, 😉😉

_Kindly follow this [link](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) for more on CSS grid and try to separate your cards as suggested by the previous Reviewer 🙏_ 

---
## Your design currently 👇 

![image](https://user-images.githubusercontent.com/102757126/216252821-3938c9b2-596d-49f6-b286-44b0c029e11d.png)

2023-02-02 07:00 UTC, TuyishimireEric commented on style.css
> +  }
- [ ] **As suggested by the previous reviewer,** I think it would be better to resize your ```popup-container``` as it's not fitting on any screen on the desktop and mobile view. 😒 Kindly make them **responsive** so they can fit on every screen and kindly avoid scrolling up and down for a better user experience. _(You could reduce the description, the image size, etc.)_ 😎

2023-02-02 09:31 UTC, Ibizugbe requested changes
Hi @Gmanlove 👋, 

![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966](https://user-images.githubusercontent.com/64643995/216285352-f109dea4-e113-4657-afea-48cfbaf73f12.gif)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅

- [ ]  GIthub flow has been used correctly👍.
- [ ]  Linters are passing👍.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-02 09:31 UTC, Ibizugbe commented on script.js
> +  </div>
NIce job making implemnting the changes requested by the previous reviewers👍,  I think your project cards currently matches the design on mobile, but on desktop it is still looking different from the given design😉. 

your project cards 
![Screenshot from 2023-02-02 10-04-04](https://user-images.githubusercontent.com/64643995/216281246-a560843e-460e-4214-8a10-7b0bc9413214.png)

currently an individual card takes almost the entire width and height of the screen, I think we can make some improvements on that, just take a look and [the design ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=fNRsCiKJ9Gq57Nqh-0)and make the comparison😉.

design
![image](https://user-images.githubusercontent.com/64643995/216282067-5416114d-2867-49fd-8185-764b5715b007.png)

kindly take a look at the spacings and make the necessary adjustments🤗
don't forget that it is a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md) for this milestone that we stick to the [given design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1&t=fNRsCiKJ9Gq57Nqh-0)

2023-02-02 09:31 UTC, Ibizugbe commented on script.js
> +}
You have done a good job implementing the popup interactions and currently, I think your popup looks good on mobile👍. but just as requested by the previous reviewers, the popup on the desktop looks different from that of the design and it is a requirement for this milestone that we stick to the design even as we make our pages responsive😉😉

your popup
![Screenshot from 2023-02-02 10-20-56](https://user-images.githubusercontent.com/64643995/216284073-1754355f-c922-481f-97bf-ad8f5ca54728.png)

design
![image](https://user-images.githubusercontent.com/64643995/216284282-fc40d11a-9c41-4074-99e4-36637f4302ed.png)
I suggest you take note of the height and width of the image and the spacings of each components as well😉

kindly observe the differences and make the necessary adjustments🤗🤗🤗.

2023-02-03 01:17 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Gmanlove, 👋 

Your project is complete! Great job for following the project requirement🥇 and implementing the changes requested by the previous reviewers. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://media.tenor.com/ipGxBQElNzYAAAAM/approved-ymaz.gif" width="500px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

### Changes Required ♻️

- [x]  _Please check the comments under the review._

### Optional Changes 🔥

- [ ] [OPTIONAL] Kindly add the `key features` and the `future feature` headings to your README file which include 1-3 things you have done or will do in your project

Thank You.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-03 01:20 UTC, merged